name: Android CI

on:
  push:
    branches:
      - 'release/**'
  workflow_dispatch:
    inputs:
      version:
        description: 'Application version'
        required: true
        default: '1.0'

env:
  APP_MODULE: app
  AAB_NAME: mini-snake-bundle
  PLAYSTORE_NAME: MiniSnake Game
  PACKAGE_NAME: de.nazmi.minisnake
  KEYSTORE: ${{ secrets.KEYSTORE }}
  SERVICE_ACCOUNT: ${{ secrets.SERVICE_ACCOUNT_JSON }}
  KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
  KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
  STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
  JAVA_VERSION: '17'

jobs:
  build:
    name: Build and Sign AAB
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v2
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Decode Keystore
        id: decode_keystore
        uses: timheuer/base64-to-file@v1.2
        with:
          fileName: 'android_keystore.jks'
          fileDir: ${{ github.workspace }}/app/keystore/
          encodedString: ${{ env.KEYSTORE }}

      - name: Build AAB
        run: |
          echo "Building AAB..."
          ./gradlew bundleRelease
        env:
          SIGNING_KEY_ALIAS: ${{ env.KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ env.KEY_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ env.STORE_PASSWORD }}

      - name: Upload AAB as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: aab-artifact
          path: app/build/outputs/bundle/release/app-release.aab

      - name: List Release Files
        run: |
          echo "Listing release files..."
          find ${{ env.APP_MODULE }}/build/outputs -type f

  release:
    name: Release to Play Store
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download AAB Artifact
        uses: actions/download-artifact@v2
        with:
          name: aab-artifact
          path: app/build/outputs/bundle/release/
      - name: Upload Play Store Release
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ env.SERVICE_ACCOUNT }}
          packageName: ${{ env.PACKAGE_NAME }}
          releaseFiles: app/build/outputs/bundle/release/app-release.aab
          track: production
          status: inProgress
          inAppUpdatePriority: 1
          userFraction: 0.33
          whatsNewDirectory: distribution/whatsnew
          mappingFile: ${{ env.APP_MODULE }}/build/outputs/mapping/release/mapping.txt
